In [12]:
import numpy as np
class App:
    def __init__(self):
        self.arr = np.random.randint(100, size=(10))
        print(self.arr)
        print("Média:", self.calcular_media())
        print("Desvio Padrão:", self.calcular_desvio_padrao())
        print("Menor e Maior:", self.maioremenor()[0], self.maioremenor()[1])

    def calcular_media(self):
        return np.mean(self.arr)
    
    def calcular_desvio_padrao(self):
        return np.std(self.arr)
    
    def maioremenor(self):
        return np.min(self.arr), np.max(self.arr)
    
App()

[45  3 74 70 85 45 93 34 93 81]
Média: 62.3
Desvio Padrão: 28.039436513596346
Menor e Maior: 3 93


In [14]:
        m1 = np.random.randint(100, size=(3, 3))
        m2 = np.random.randint(100, size=(3, 3))
        print("Matriz 1:\n", m1)
        print("Produto da matriz 1:\n", np.dot(m1, m1))
        print("Matriz 2:\n", m2)
        print("Produto da matriz 2:\n", np.dot(m2, m2))
        print("Produto das Matrizes:\n", np.dot(m1, m2))


Matriz 1:
 [[20  4 89]
 [17 46 14]
 [52 13 55]]
Produto da matriz 1:
 [[5096 1421 6731]
 [1850 2366 2927]
 [4121 1521 7835]]
Matriz 2:
 [[40 14 81]
 [35 54  7]
 [54 41 26]]
Produto da matriz 2:
 [[6464 4637 5444]
 [3668 3693 3395]
 [4999 4036 5337]]
Produto das Matrizes:
 [[5746 4145 3962]
 [3046 3296 2063]
 [5505 3685 5733]]


In [17]:
        arr = np.linspace(0, np.pi, 50)
        print("Valores Espaçados:\n", arr)
        print("Seno dos Valores Espaçados:\n", np.sin(arr))
        print("Cosseno dos Valores Espaçados:\n", np.cos(arr))

Valores Espaçados:
 [0.         0.06411414 0.12822827 0.19234241 0.25645654 0.32057068
 0.38468481 0.44879895 0.51291309 0.57702722 0.64114136 0.70525549
 0.76936963 0.83348377 0.8975979  0.96171204 1.02582617 1.08994031
 1.15405444 1.21816858 1.28228272 1.34639685 1.41051099 1.47462512
 1.53873926 1.60285339 1.66696753 1.73108167 1.7951958  1.85930994
 1.92342407 1.98753821 2.05165235 2.11576648 2.17988062 2.24399475
 2.30810889 2.37222302 2.43633716 2.5004513  2.56456543 2.62867957
 2.6927937  2.75690784 2.82102197 2.88513611 2.94925025 3.01336438
 3.07747852 3.14159265]
Seno dos Valores Espaçados:
 [0.00000000e+00 6.40702200e-02 1.27877162e-01 1.91158629e-01
 2.53654584e-01 3.15108218e-01 3.75267005e-01 4.33883739e-01
 4.90717552e-01 5.45534901e-01 5.98110530e-01 6.48228395e-01
 6.95682551e-01 7.40277997e-01 7.81831482e-01 8.20172255e-01
 8.55142763e-01 8.86599306e-01 9.14412623e-01 9.38468422e-01
 9.58667853e-01 9.74927912e-01 9.87181783e-01 9.95379113e-01
 9.99486216e-01 9.9948621